household_power_consumption <- read.csv("household_power_consumption.txt", sep=";")
DateIndex<-grep("^1/2/2007|^2/2/2007",household_power_consumption[,1])
SelectedDate<-household_power_consumption[DateIndex,]
SelectedDate$DateTime <- strptime(paste(SelectedDate$Date, SelectedDate$Time), "%d/%m/%Y %H:%M:%S") 
png(filename = "plot3.png",width = 480, height = 480, units = "px")
plot(SelectedDate$DateTime,as.numeric(as.character(SelectedDate$Sub_metering_1)),type="l",xlab='',ylab='Energy sub metering')
lines(SelectedDate$DateTime,as.numeric(as.character(SelectedDate$Sub_metering_2)),type="l",col="red")
lines(SelectedDate$DateTime,as.numeric(as.character(SelectedDate$Sub_metering_3)),type="l",col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1)
dev.off()
